tracker_label = 'D3S';

tracker_command = generate_python_command('vot_wrapper_sk', ...
    {'/home/slz/GitHub/d3s', ...
    '/home/slz/GitHub/d3s/pytracking', ...
    '/home/slz/GitHub/vot-toolkit/native/trax/support/python'});

tracker_interpreter = 'python';

tracker_linkpath = {'/home/slz/GitHub/vot-toolkit/native/trax/support/python', ...
     '/home/slz/GitHub/vot-toolkit/native/trax/support/python/trax'};
